language: python
python:
  - "3.4"
  - "3.6"
before_install:
  - mkdir .sis
  - cd .sis
install: 
  - git clone https://github.com/intelecto/extractor ~/.sis
  - pip install -r requirements.txt
  - pip install codecov
script:
  - python test_extractor.py
after_success: 
  - coverage run test_extractor.py
  - codecov
notifications:
    email: true
